export default {
	GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
	GET_INPUT:"GET_INPUT",
	TOGGLE_SEARCH_RESULT:"TOGGLE_SEARCH_RESULT",
	GET_ADDRESS_PREDICTIONS:"GET_ADDRESS_PREDICTIONS",
	GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
	GET_DISTANCE_MATRIX:"GET_DISTANCE_MATRIX",
	GET_FARE:"GET_FARE",
	BOOK_CAR:"BOOK_CAR",
	GET_NEARBY_DRIVERS:"GET_NEARBY_DRIVERS",
	ROUTE_POINTS: 'ROUTE_POINTS',
	ROUTE_POINTS_LOADING: 'ROUTE_POINTS_LOADING',
	CLEAR_INPUT: 'CLEAR_INPUT'
};